### PR TITLE
adding Jest and a simple tdd test as example

### PR DESCRIPTION
**Pull request by linediconsine**
Hi, I hope this ok for you 

I made some simple adds
- Jest
- scripts in package.json for Jest
```
   "test" : "jest",
   "test:watch" : "jest --watch"
   "test:coverage": "jest --coverage"
```
- added a simple example of test

### CODE REVIEW

**Comment by themetalfleece** [comment]
Hey there! Thanks for your contribution, Seems like a great addition!

I have a couple of comments:
1) I don't like how both `yarn.lock` and `package-lock.json` are commited. Maybe we should remove both, and let them be generated when the user runs `yarn` or `npm i` for the first time?
2) Testing-related packages (`@types/jest`, `jest`, `ts-jest`) should be in `devDependencies`

Also, maybe we should describe the `sum.ts`, and `sum.spec.tsc` files in README (`What to do after using this template` section) - so users can know that it's a placeholder file and a test associated with it.

**Comment by linediconsine** [comment]
In my last commit in this PR I:
- removed lock files and added in  .gitignore
- moved @types/jest, jest, ts-jest in devDependencies
- Referenced sum.ts and sum.spec.ts in the readme.md

**Comment by themetalfleece** [comment]
> In my last commit in this PR I:
> 
> * removed lock files and added in  .gitignore
> * moved @types/jest, jest, ts-jest in devDependencies
> * Referenced sum.ts and sum.spec.ts in the readme.md

Awesome. One minor change though, that I didn't comunicate effectively:
I believe that the lock files shouldn't be put in `.gitignore`, since the users of the template should push them. So, I think that they should not be ignored, and we'll just not push them here!

**Comment by linediconsine** [comment]
Good catch!

Done

**Review by themetalfleece — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
